#!/usr/bin/env python3
"""Regenerate src/client.resid from assets/datastar.js.

The bundle is embedded as string literals so a server built with the SDK
serves the client without reading a file. Its SHA-256 and SHA-384 (the
subresource-integrity form) are recorded beside it and checked by the tests.
"""
import base64, hashlib, pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
js = (root / "assets" / "datastar.js").read_bytes()
text = js.decode("ascii")
first = text.split("\n", 1)[0]
if not first.startswith("// Datastar v"):
    sys.exit("assets/datastar.js does not start with its version line")
version = first[len("// Datastar v"):].strip()
sha256 = hashlib.sha256(js).hexdigest()
sri = "sha384-" + base64.b64encode(hashlib.sha384(js).digest()).decode()


def lit(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


parts = [text[i:i + 2048] for i in range(0, len(text), 2048)]
body = "\n        + ".join(lit(p) for p in parts)
out = f"""// ─── src/client.resid — the Datastar client, embedded ──────────────────
// Generated by tools/embed_client.py from assets/datastar.js; do not edit.

// The client's version, as its first line names it.
pub Str ds_client_version() {{ return "{version}"; }}

// SHA-256 of the bundle, hex.
pub Str ds_client_sha256() {{ return "{sha256}"; }}

// The subresource-integrity value of the bundle (SHA-384).
pub Str ds_client_integrity() {{ return "{sri}"; }}

// The bundle's text.
pub Str ds_client_js() {{
    return {body};
}}
"""
(root / "src" / "client.resid").write_text(out)
print(f"src/client.resid: Datastar {version}, {len(js)} bytes, sha256 {sha256}")
